In [ ]:
import torch as pt
import numpy as np
import pandas as pd


path = "/content/drive/MyDrive/Internship/"
df = pd.read_csv(path + "data_mod.csv")
print(df)





      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors
0    313000         3       1.50         1340      7912     1.5
1   2384000         5       2.50         3650      9050     2.0
2    342000         3       2.00         1930     11947     1.0
3    420000         3       2.25         2000      8030     1.0
4    550000         4       2.50         1940     10500     1.0
..      ...       ...        ...          ...       ...     ...
94   524000         3       1.75         1560      5520     1.0
95   541125         5       2.75         2740      8426     1.0
96   670000         3       2.50         1680      2000     3.0
97   384900         5       2.50         3090     12750     1.0
98   406100         3       2.25         1410      1332     3.0

[99 rows x 6 columns]


In [ ]:
tensor = pt.tensor(df.values)
x = tensor[:,1:]
y = tensor[:,0]
y = y.reshape(-1,1)

print(f"Values of features as tensor before nomalization:\n{x}")
print(x.shape)
print(f"\nValue of output as tensor before normlaization:\n{y}")
print(y.shape)

Values of features as tensor:
tensor([[3.0000e+00, 1.5000e+00, 1.3400e+03, 7.9120e+03, 1.5000e+00],
        [5.0000e+00, 2.5000e+00, 3.6500e+03, 9.0500e+03, 2.0000e+00],
        [3.0000e+00, 2.0000e+00, 1.9300e+03, 1.1947e+04, 1.0000e+00],
        [3.0000e+00, 2.2500e+00, 2.0000e+03, 8.0300e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 1.9400e+03, 1.0500e+04, 1.0000e+00],
        [2.0000e+00, 1.0000e+00, 8.8000e+02, 6.3800e+03, 1.0000e+00],
        [2.0000e+00, 2.0000e+00, 1.3500e+03, 2.5600e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 2.7100e+03, 3.5868e+04, 2.0000e+00],
        [3.0000e+00, 2.5000e+00, 2.4300e+03, 8.8426e+04, 1.0000e+00],
        [4.0000e+00, 2.0000e+00, 1.5200e+03, 6.2000e+03, 1.5000e+00],
        [3.0000e+00, 1.7500e+00, 1.7100e+03, 7.3200e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 2.9200e+03, 4.0000e+03, 1.5000e+00],
        [3.0000e+00, 1.7500e+00, 2.3300e+03, 1.4892e+04, 1.0000e+00],
        [3.0000e+00, 1.0000e+00, 1.0900e+03, 6.4350e+03, 1.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalerX = MinMaxScaler()
x_norm = scalerX.fit_transform(x)
scalerY = MinMaxScaler()
y_norm = scalerY.fit_transform(y)
x = pt.from_numpy(x_norm)
y = pt.from_numpy(y_norm)

print(f"Values of features as tensor after nomalization:\n{x}")
print(x.shape)
print(f"\nValue of output as tensor after normlaization:\n{y}")
print(y.shape)

Values of features as tensor after nomalization:
tensor([[2.5000e-01, 2.2222e-01, 1.8685e-01, 5.4210e-02, 2.5000e-01],
        [7.5000e-01, 6.6667e-01, 9.8616e-01, 6.3367e-02, 5.0000e-01],
        [2.5000e-01, 4.4444e-01, 3.9100e-01, 8.6677e-02, 0.0000e+00],
        [2.5000e-01, 5.5556e-01, 4.1522e-01, 5.5159e-02, 0.0000e+00],
        [5.0000e-01, 6.6667e-01, 3.9446e-01, 7.5034e-02, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.7682e-02, 4.1882e-02, 0.0000e+00],
        [0.0000e+00, 4.4444e-01, 1.9031e-01, 1.1144e-02, 0.0000e+00],
        [5.0000e-01, 6.6667e-01, 6.6090e-01, 2.7916e-01, 5.0000e-01],
        [2.5000e-01, 6.6667e-01, 5.6401e-01, 7.0207e-01, 0.0000e+00],
        [5.0000e-01, 4.4444e-01, 2.4913e-01, 4.0434e-02, 2.5000e-01],
        [2.5000e-01, 3.3333e-01, 3.1488e-01, 4.9446e-02, 0.0000e+00],
        [5.0000e-01, 6.6667e-01, 7.3356e-01, 2.2731e-02, 2.5000e-01],
        [2.5000e-01, 3.3333e-01, 5.2941e-01, 1.1037e-01, 0.0000e+00],
        [2.5000e-01, 0.0000e+00, 1.0035e-

In [ ]:
def hypothesis(x,weights,bias):
  return x @ weights + bias

def cost_calculator(preds,y):
    m = len(y)
    errors = preds - y
    cost = (1 / (2 * m)) * pt.sum(errors ** 2)
    return cost

def precent_calc(iCost, fCost ):
  return ((iCost - fCost)/iCost)*100

In [ ]:
pt.manual_seed(44)
weights = pt.randn(5,1,requires_grad=True, dtype=pt.float64)
bias = pt.randn(1,requires_grad=True,dtype=pt.float64 )
preds = hypothesis(x,weights,bias)
cost = cost_calculator(preds,y)
initial_cost = cost


print(f"Initial cost: {cost}")
print(f"\nInitial weights: \n{weights}")
print(f"\nInitial bias: \n{bias}")
print(f"\nPredicted Output values: \n{preds}")
print(preds.shape)

Initial cost: 0.9773365967640137

Initial weights: 
tensor([[ 0.0589],
        [-1.3945],
        [ 0.8448],
        [ 0.1268],
        [ 1.0822]], dtype=torch.float64, requires_grad=True)

Initial bias: 
tensor([-1.1731], dtype=torch.float64, requires_grad=True)

Predicted Output values: 
tensor([[-1.0329],
        [-0.6763],
        [-1.4368],
        [-1.5753],
        [-1.7305],
        [-1.1444],
        [-1.6307],
        [-0.9384],
        [-1.5225],
        [-1.2772],
        [-1.3509],
        [-1.1801],
        [-1.1619],
        [-1.0682],
        [-1.3176],
        [-1.3426],
        [-1.2375],
        [-1.1606],
        [-1.4518],
        [-1.3479],
        [-0.6515],
        [-0.9458],
        [-0.8433],
        [-0.9567],
        [-1.3693],
        [-1.7011],
        [-1.1609],
        [-1.2282],
        [-0.8592],
        [-1.5582],
        [-1.3786],
        [-0.9278],
        [-1.1908],
        [-0.9343],
        [-0.9329],
        [-0.8010],
        [-1.1693],
      

In [ ]:
alpha = 1e-1
iterations = 10000
for i in range(iterations):
  preds = hypothesis(x,weights,bias)
  cost = cost_calculator(preds,y)
  if i%1000 == 0:
    print(f"Cost at iteration {i} is {cost}")
  cost.backward()
  with pt.no_grad():
    weights -= alpha * weights.grad
    bias -= alpha * bias.grad
    weights.grad.zero_()
    bias.grad.zero_()

percentage = precent_calc(initial_cost,cost)

print(f"\nFinal cost: {cost}")
print(f"\nComparing Inital and Final Costs:\n     Initial Cost = {initial_cost}\n     Final Cost   = {cost}\nThere has been {percentage:.2f} % decrease in Cost! ")


print(f"\nFinal weights: \n{weights}")
print(f"\nFinal bias: \n{bias}")

Cost at iteration 0 is 0.9773365967640137
Cost at iteration 1000 is 0.005751276667835142
Cost at iteration 2000 is 0.005570002635471323
Cost at iteration 3000 is 0.005567104177065947
Cost at iteration 4000 is 0.005567034683451794
Cost at iteration 5000 is 0.005567032862219627
Cost at iteration 6000 is 0.005567032812793144
Cost at iteration 7000 is 0.005567032811427767
Cost at iteration 8000 is 0.005567032811389703
Cost at iteration 9000 is 0.005567032811388638

Final cost: 0.005567032811388606

Comparing Inital and Final Costs:
     Initial Cost = 0.9773365967640137
     Final Cost   = 0.005567032811388606
There has been 99.43 % decrease in Cost! 

Final weights: 
tensor([[ 0.0958],
        [-0.0923],
        [ 0.2639],
        [-0.0704],
        [ 0.0679]], dtype=torch.float64, requires_grad=True)

Final bias: 
tensor([0.0350], dtype=torch.float64, requires_grad=True)
